title: Tiffany Sia Chong
owner: Tiffany Sia Chong
blogTitle: Already Past Midnight
email: hello@sciffany.com
description: >-
  Computer Science Student.
  Software Engineer.
  Graphic Designer.
  Animator.
baseurl: ""
# hostname
url: "sciffany.com"
github_username: sciffany
linkedin_username: sciffany

theme: minima
plugins:
  - jekyll-feed

links:
  - title: Experience
    url: experience/
  - title: Projects
    url: projects/
  - title: Games
    url: games/
  - title: Design
    url: design/
  - title: Blog
    url: blog/

blogLinks:
  - title: Blog
    url : blog/
  - title: Applets
    url : blog/applets/
  - title: About
    url: blog/about/

# Disqus Comments
disqus:
  shortname: sciffany-github-io
highlighter: rouge

# Sitemap
plugins:
  - jekyll-sitemap
